# Generated by Django 3.1.5 on 2021-01-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset',
            field=models.FileField(default='NULL', upload_to='datasets/'),
        ),
    ]
